replicas: 10

configmap:
  data:
    CUSTOM_HEADER: 'This is on the DEV environment!'

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
